<?php
return array(
    //可设置的首页.
    'sitePage' => array(
        '1'  => '1.我的首页',
        '2'  => '2.广播大厅/同城广播',
        '3'  => '3.我的广播',
        '4'  => '4.提到我的',
        '5'  => '5.我的收藏',
        '6'  => '6.私信(收件箱/发件箱)',
        '7'  => '7.我收听的人/我的听众',
        '8'  => '8.话题墙',
        '9'  => '9.名人墙',
        '10' => '10.搜索结果页'
    ),

    //组件的类型
    'components' => array(
        'main' => array(
            'todayrecommend' => array('type'   => '每日推荐',
                                      'styles' => 1,
                                      'model'  => 'Model_TodayRecommend',
                                      'desc'   => '',
                                     ),
            'recommend'      => array('type'   => '推荐用户',
                                      'styles' => 2,
                                      'model'  => 'Model_Recommend',
                                      'desc'   => '',
                                     ),
            'viprecommend'   => array('type'   => '名人推荐',
                                      'styles' => 2,
                                      'model'  => 'Model_Viprecommend',
                                      'desc'   => '',
                                     ),
            'banner'         => array('type'   => '广告管理',
                                      'styles' => 1,
                                      'model'  => 'Model_Banner',
                                      'desc'   => '',
                                     ),
            'hottopic'       => array('type'   => '热门话题',
                                      'styles' => 2,
                                      'model'  => 'Model_Hottopic',
                                      'desc'   => '',
                                     ),
            'todayvip'       => array('type'   => '今日名人',
                                      'styles' => 1,
                                      'model' => 'Model_Todayvip',
                                      'desc'   => '【今日名人】组件显示的微博账号将随机从您设置的条数中随机显示一个.',
                                     ),
        ),
        'right' => array(
            'hottopic'       => array('type'   => '热门话题',
                                      'styles' => 3,
                                      'model'  => 'Model_Hottopic',
                                      'desc'   => '',
                                     ),
            'recommend'      => array('type'   => '推荐用户',
                                      'styles' => 2,
                                      'model'  => 'Model_Recommend',
                                      'desc'   => '',
                                     ),
            'viprecommend'   => array('type'   => '名人推荐',
                                      'styles' => 2,
                                      'model'  => 'Model_Viprecommend',
                                      'desc'   => '',
                                     ),
            'fansranking'    => array('type'   => '排行榜',
                                      'styles' => 2,
                                      'model'  => 'Model_Ranking',
                                      'desc'   => '',
                                     ),
            'brand'          => array('type'   => '推荐品牌',
                                      'styles' => 2,
                                      'model'  => 'Model_Brand',
                                      'desc'   => '',
                                     ),
            'hottags'        => array('type'   => '热门标签',
                                      'styles' => 1,
                                      'model'  => 'Model_Mb_Tag',
                                      'desc'   => '',
                                     )
        )
    )
);
